name: Sync Secrets to Public_Workflows

# ⚠️ THIS FILE SHOULD BE PLACED IN THE YOUTUBE-AUTOMATION REPOSITORY
# Path: .github/workflows/sync-secrets-to-public-workflows.yml

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set Secrets in Public_Workflows
        env:
          GH_TOKEN: ${{ secrets.YOUTUBE_BOT_GITHUB_TOKEN }}
        run: |
          echo "Setting secrets in Public_Workflows repository..."
          
          # API Keys
          [ -n "${{ secrets.GOOGLE_API_KEY }}" ] && echo "${{ secrets.GOOGLE_API_KEY }}" | gh secret set GOOGLE_API_KEY --repo GiridharSalana/Public_Workflows || true
          [ -n "${{ secrets.COHERE_API_KEY }}" ] && echo "${{ secrets.COHERE_API_KEY }}" | gh secret set COHERE_API_KEY --repo GiridharSalana/Public_Workflows || true
          [ -n "${{ secrets.CEREBRAS_API_KEY }}" ] && echo "${{ secrets.CEREBRAS_API_KEY }}" | gh secret set CEREBRAS_API_KEY --repo GiridharSalana/Public_Workflows || true
          [ -n "${{ secrets.NEWSAPI_KEY }}" ] && echo "${{ secrets.NEWSAPI_KEY }}" | gh secret set NEWSAPI_KEY --repo GiridharSalana/Public_Workflows || true
          [ -n "${{ secrets.PEXELS_API_KEY }}" ] && echo "${{ secrets.PEXELS_API_KEY }}" | gh secret set PEXELS_API_KEY --repo GiridharSalana/Public_Workflows || true
          [ -n "${{ secrets.PIXABAY_API_KEY }}" ] && echo "${{ secrets.PIXABAY_API_KEY }}" | gh secret set PIXABAY_API_KEY --repo GiridharSalana/Public_Workflows || true
          
          # Telegram
          [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ] && echo "${{ secrets.TELEGRAM_BOT_TOKEN }}" | gh secret set TELEGRAM_BOT_TOKEN --repo GiridharSalana/Public_Workflows || true
          [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ] && echo "${{ secrets.TELEGRAM_CHAT_ID }}" | gh secret set TELEGRAM_CHAT_ID --repo GiridharSalana/Public_Workflows || true
          
          # GitHub Token
          [ -n "${{ secrets.YOUTUBE_BOT_GITHUB_TOKEN }}" ] && echo "${{ secrets.YOUTUBE_BOT_GITHUB_TOKEN }}" | gh secret set YOUTUBE_BOT_GITHUB_TOKEN --repo GiridharSalana/Public_Workflows || true
          
          echo "✅ All secrets have been synced to Public_Workflows"

      - name: Sync YouTube OAuth Credentials
        env:
          GH_TOKEN: ${{ secrets.YOUTUBE_BOT_GITHUB_TOKEN }}
        run: |
          # These need to be base64 encoded in the source repo
          [ -n "${{ secrets.YOUTUBE_CREDENTIALS_JSON }}" ] && echo "${{ secrets.YOUTUBE_CREDENTIALS_JSON }}" | gh secret set YOUTUBE_CREDENTIALS_JSON --repo GiridharSalana/Public_Workflows || true
          [ -n "${{ secrets.YOUTUBE_TOKEN_PICKLE }}" ] && echo "${{ secrets.YOUTUBE_TOKEN_PICKLE }}" | gh secret set YOUTUBE_TOKEN_PICKLE --repo GiridharSalana/Public_Workflows || true
          
          echo "✅ YouTube OAuth credentials synced"

      - name: Cleanup
        if: always()
        run: |
          echo "✅ Sync completed"

