name: Sync Secrets to Public_Workflows

# ⚠️ THIS FILE SHOULD BE PLACED IN THE BLOGGER-AUTOMATION REPOSITORY
# Path: .github/workflows/sync-secrets-to-public-workflows.yml

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Secrets JSON
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          CEREBRAS_API_KEY: ${{ secrets.CEREBRAS_API_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          IMGBB_CLIENT_ID: ${{ secrets.IMGBB_CLIENT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BLOGGER_BOT_GITHUB_TOKEN: ${{ secrets.BLOGGER_BOT_GITHUB_TOKEN }}
        run: |
          # Create JSON with all secrets (excluding empty ones)
          cat > secrets.json << 'EOF'
          {
            "GOOGLE_API_KEY": "$GOOGLE_API_KEY",
            "COHERE_API_KEY": "$COHERE_API_KEY",
            "CEREBRAS_API_KEY": "$CEREBRAS_API_KEY",
            "BLOG_ID": "$BLOG_ID",
            "LINKEDIN_ACCESS_TOKEN": "$LINKEDIN_ACCESS_TOKEN",
            "IMGBB_CLIENT_ID": "$IMGBB_CLIENT_ID",
            "TELEGRAM_BOT_TOKEN": "$TELEGRAM_BOT_TOKEN",
            "TELEGRAM_CHAT_ID": "$TELEGRAM_CHAT_ID",
            "BLOGGER_BOT_GITHUB_TOKEN": "$BLOGGER_BOT_GITHUB_TOKEN"
          }
          EOF
          
          # Substitute environment variables
          envsubst < secrets.json > secrets_expanded.json
          
          # Remove entries with empty values
          jq 'with_entries(select(.value != ""))' secrets_expanded.json > secrets_final.json
          
          # Base64 encode for secure transmission
          cat secrets_final.json | base64 -w 0 > secrets_encoded.txt
          
          echo "✅ Secrets prepared for sync"

      - name: Set Secrets in Public_Workflows
        env:
          GH_TOKEN: ${{ secrets.BLOGGER_BOT_GITHUB_TOKEN }}
        run: |
          # Read each secret and set it directly in Public_Workflows
          echo "Setting secrets in Public_Workflows repository..."
          
          [ -n "${{ secrets.GOOGLE_API_KEY }}" ] && echo "${{ secrets.GOOGLE_API_KEY }}" | gh secret set GOOGLE_API_KEY --repo GiridharSalana/Public-Workflows || true
          [ -n "${{ secrets.COHERE_API_KEY }}" ] && echo "${{ secrets.COHERE_API_KEY }}" | gh secret set COHERE_API_KEY --repo GiridharSalana/Public-Workflows || true
          [ -n "${{ secrets.CEREBRAS_API_KEY }}" ] && echo "${{ secrets.CEREBRAS_API_KEY }}" | gh secret set CEREBRAS_API_KEY --repo GiridharSalana/Public-Workflows || true
          [ -n "${{ secrets.BLOG_ID }}" ] && echo "${{ secrets.BLOG_ID }}" | gh secret set BLOG_ID --repo GiridharSalana/Public-Workflows || true
          [ -n "${{ secrets.LINKEDIN_ACCESS_TOKEN }}" ] && echo "${{ secrets.LINKEDIN_ACCESS_TOKEN }}" | gh secret set LINKEDIN_ACCESS_TOKEN --repo GiridharSalana/Public-Workflows || true
          [ -n "${{ secrets.IMGBB_CLIENT_ID }}" ] && echo "${{ secrets.IMGBB_CLIENT_ID }}" | gh secret set IMGBB_CLIENT_ID --repo GiridharSalana/Public-Workflows || true
          [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ] && echo "${{ secrets.TELEGRAM_BOT_TOKEN }}" | gh secret set TELEGRAM_BOT_TOKEN --repo GiridharSalana/Public-Workflows || true
          [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ] && echo "${{ secrets.TELEGRAM_CHAT_ID }}" | gh secret set TELEGRAM_CHAT_ID --repo GiridharSalana/Public-Workflows || true
          [ -n "${{ secrets.BLOGGER_BOT_GITHUB_TOKEN }}" ] && echo "${{ secrets.BLOGGER_BOT_GITHUB_TOKEN }}" | gh secret set BLOGGER_BOT_GITHUB_TOKEN --repo GiridharSalana/Public-Workflows || true
          
          echo "✅ All secrets have been synced to Public_Workflows"

      - name: Cleanup
        if: always()
        run: |
          rm -f secrets*.json secrets_encoded.txt
          echo "✅ Cleaned up temporary files"

